baseURL: 'https://ukreu.org/'
languageCode: 'en-us'
theme: 'bs5'
publishdir: 'docs'


defaultContentLanguage: ua
languages:
  ua:
    title: 'Біженство українцям'
    description: 'Допомога інформаційна українцям по питанням біженства'
    weight: 2
  ru:
    title: 'Беженство украинцам'
    description: 'Помощь украинцам по вопросам беженства'
    weight: 1

