baseURL: 'https://ukreu.org/'
languageCode: 'en-us'
theme: 'bs5'
publishdir: 'docs'


defaultContentLanguage: ua
languages:
  ua:
    title: 'Біженство українцям'
    description: 'Допомога інформаційна українцям по питанням біженства'
    weight: 2
    copyright: '© 2022 Допомога українцям'
    params:
      bigTitle: 'Допомога українцям по питанням біженства'
      dateTitle: 'Дата актуалізації'
      green:
        title: 'Зелений блок'
        descriptions:
          - 'Інформація в цьому бюлетні надана на зеленому фоні є достовірною і обновлюється кожного дня.'
      yellow:
        title: 'Жовтий блок'
        descriptions:
          - 'Інформація на жовтому фоні є ВИКЛЮЧНО ДЛЯ ОЗНАЙОМЛЕННЯ, обновлюється у міру можливостей. В силу того, що країни активно змінюють законодавство, щоб допомогти біженцям - ми можем не встигати її актуалізувать.'
          - 'Після ознайомлення перевіряйте актуальну інформацію за посиланнями та горячим лінія, наданим в рамках зеленої секції країн, що вас цікавлять.'
  ru:
    title: 'Беженство украинцам'
    description: 'Помощь украинцам по вопросам беженства'
    weight: 1
    copyright: '© 2021 Помощь украинцам'
    params:
      bigTitle: 'Помощь украинцам по вопросам беженства'
      dateTitle: 'Дата актуализации'
      green:
        title: 'Зеленый блок'
        descriptions:
          - 'Информация в этом бюллетене предоставлена на зеленом фоне является достоверной и обновляется на ежедневной основе.'
      yellow:
        title: 'Желтый блок'
        descriptions:
          - 'Информация на желтом фоне является ИСКЛЮЧИТЕЛЬНО ОЗНАКОМИТЕЛЬНОЙ, обновляется по мере возможностей. В силу того, что страны активно меняют законодательства, чтобы помочь беженцам - мы можем не успевать ее актуализировать.'
          - 'После ознакомления проверяйте актуальную информацию по ссылкам и горячим линиям, предоставленным в рамках зеленой секции интересующей вас страны.'

