baseURL: 'https://ukreu.org/'
languageCode: 'en-us'
theme: 'bs5'
params:
  description: ""
publishdir: 'docs'


defaultContentLanguage: ua
languages:
  ua:
    title: 'Допомога українцям по питанням біженства'
    weight: 2
  ru:
    title: 'Помощь украинцам по вопросам беженства'
    weight: 1

